version: '3.7'
volumes:
  postgres-data:
services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - DB_NAME=PerfectParty_development
    ports:
      - 5432:5432
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - RAILS_ENV=development
      - DB_NAME=PerfectParty_development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/perfectparty
    ports:
      - "3000:3000"
    depends_on:
      - db